name: CICD

on:
  push:
    branches: [main]

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code checkout"
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code build"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code Test"
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code Deploy"
        
