name: CICD

on:
  workflow_dispatch:
    inputs:
      environments:
        description: This is Environment variable trigger when inputs provides
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - stagging

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code checkout"
  Build:
    runs-on: ubuntu-latest
    needs: [Code]
    steps:
      - name: Build code
        run: echo "code build"
  Test:
    runs-on: ubuntu-latest
    needs: [Code,Build]
    steps:
      - name: Test code
        run: echo "code Test"
  Deploy:
    if: inputs.environments == 'dev'
    needs: [Code,Build,Test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "code Deploy"
        
