name: CICD

on:
  push:
    branches: [main]

jobs:
  Code:
    runs-on: ubuntu-latest
    steps:
      - name: cehckout code
        run: echo "code checkout"
  Build:
    runs-on: ubuntu-latest
    needs: [Code]
    steps:
      - name: Build code
        run: echo "code build"
  Test:
    runs-on: ubuntu-latest
    needs: [Code,Build]
    steps:
      - name: Test code
        run: echo "code Test"
  Deploy:
    needs: [Code,Build,Test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "code Deploy"
        
